import type { SkeletonState, StudioPreset } from "../types";

export const DEFAULT_SKELETON_STATE: SkeletonState = {
  title: "Loading dashboard cards",
  description: "Visible placeholder structure while dashboard data is being fetched.",
  label: "Dashboard loading state",
  helper: "Decorative skeleton pieces are hidden from assistive tech while the container reports loading.",
  id: "dashboard-skeleton",
  ariaLabel: "Dashboard content is loading",
  tabIndex: 0,
  width: 560,
  height: 360,
  gap: 14,
  padding: 24,
  radius: 22,
  borderWidth: 1,
  borderStyle: "solid",
  fontBucket: "google",
  fontSearch: "",
  systemFontIdx: 9,
  googleFontFamily: "Inter",
  fontSizeUnit: "px",
  fontStyle: "normal",
  textTransform: "none",
  textDecoration: "none",
  letterSpacing: 0,
  letterSpacingUnit: "px",
  lineHeight: 1.5,
  radiusLinked: true,
  radiusTL: 22,
  radiusTR: 22,
  radiusBR: 22,
  radiusBL: 22,
  shadowEnabled: true,
  shadowX: 0,
  shadowY: 8,
  shadowBlur: 24,
  shadowSpread: 0,
  shadowOpacity: 0.25,
  shadowColor: "#000000",
  focusRingEnabled: true,
  focusRingWidth: 2,
  focusRingOffset: 2,
  focusRingColor: "#38bdf8",
  transitionDuration: 200,
  transitionEasing: "ease",
  background: "#0f172a",
  foreground: "#e5eefb",
  muted: "#64748b",
  accent: "#38bdf8",
  border: "#334155",
  titleSize: 22,
  bodySize: 14,
  fontWeight: 700,
  previewState: "loading",
  disabled: false,
  disabledOpacity: 0.5,
  disabledCursor: "not-allowed",
  disabledUseCustomColors: false,
  disabledBg: "#374151",
  disabledText: "#9ca3af",
  disabledBorder: "#4b5563",
  role: "status",
  pattern: "card",
  lineCount: 4,
  showAvatar: true,
  showMedia: true,
  animation: "shimmer",
  duration: 1400,
  reducedMotion: false,
};

const presets: Array<Omit<StudioPreset, "state"> & { state: Partial<SkeletonState> }> = [
  {
    id: "dashboard-card-shimmer",
    family: "saas",
    archetype: "Dashboard",
    variant: "card",
    size: "spacious",
    tags: ["card", "avatar", "media", "shimmer"],
    state: {},
  },
  {
    id: "feed-avatar-rows",
    family: "social",
    archetype: "Feed",
    variant: "avatar",
    size: "compact",
    tags: ["avatar", "rows", "reduced-motion-safe"],
    state: {
      title: "Loading activity feed",
      description: "Avatar and text-line placeholders for incoming activity items.",
      label: "Activity feed loading",
      helper: "Avatar skeletons are decorative; the status label announces the load.",
      id: "activity-feed-skeleton",
      ariaLabel: "Activity feed is loading",
      width: 460,
      height: 300,
      padding: 20,
      background: "#f8fafc",
      foreground: "#0f172a",
      muted: "#cbd5e1",
      accent: "#2563eb",
      border: "#e2e8f0",
      pattern: "avatar",
      lineCount: 5,
      showAvatar: true,
      showMedia: false,
      animation: "fade",
      duration: 1200,
    },
  },
  {
    id: "article-text-static",
    family: "editorial",
    archetype: "Article",
    variant: "text",
    size: "spacious",
    tags: ["text", "static", "reduced-motion"],
    state: {
      title: "Loading article",
      description: "Static text-line placeholders for a long-form document.",
      label: "Article loading",
      helper: "Static mode avoids unnecessary motion for reading contexts.",
      id: "article-skeleton",
      ariaLabel: "Article content is loading",
      background: "#fffbeb",
      foreground: "#451a03",
      muted: "#fde68a",
      accent: "#d97706",
      border: "#fcd34d",
      pattern: "text",
      lineCount: 7,
      showAvatar: false,
      showMedia: false,
      animation: "none",
      duration: 0,
      reducedMotion: true,
    },
  },
  {
    id: "media-card-loading",
    family: "commerce",
    archetype: "Product",
    variant: "media",
    size: "spacious",
    tags: ["media", "card", "product"],
    state: {
      title: "Loading product preview",
      description: "Media block, title, price, and metadata placeholders.",
      label: "Product card loading",
      helper: "Media skeleton reserves image space to reduce layout shift.",
      id: "product-card-skeleton",
      ariaLabel: "Product preview is loading",
      background: "#111827",
      foreground: "#f9fafb",
      muted: "#4b5563",
      accent: "#f97316",
      border: "#374151",
      pattern: "card",
      lineCount: 3,
      showAvatar: false,
      showMedia: true,
      animation: "shimmer",
      duration: 1600,
    },
  },
  {
    id: "table-region-loading",
    family: "admin",
    archetype: "Table",
    variant: "rows",
    size: "spacious",
    tags: ["table", "rows", "aria-busy"],
    state: {
      title: "Loading users table",
      description: "Row and cell placeholders for a busy data region.",
      label: "Users table loading",
      helper: "Region role uses aria-busy to describe the loading section.",
      id: "users-table-skeleton",
      ariaLabel: "Users table is loading",
      background: "#ecfdf5",
      foreground: "#052e16",
      muted: "#a7f3d0",
      accent: "#10b981",
      border: "#6ee7b7",
      role: "region",
      pattern: "table",
      lineCount: 6,
      showAvatar: false,
      showMedia: false,
      animation: "fade",
      duration: 1100,
    },
  },
  {
    id: "compact-chip-lines",
    family: "system",
    archetype: "Inline",
    variant: "compact",
    size: "compact",
    tags: ["compact", "lines", "status"],
    state: {
      title: "Loading filters",
      description: "Compact lines for inline filter and chip placeholders.",
      label: "Filter controls loading",
      helper: "Compact skeleton keeps the busy status in a small footprint.",
      id: "filters-skeleton",
      ariaLabel: "Filter controls are loading",
      width: 420,
      height: 220,
      padding: 18,
      background: "#18181b",
      foreground: "#fafafa",
      muted: "#52525b",
      accent: "#a78bfa",
      border: "#3f3f46",
      pattern: "text",
      lineCount: 4,
      showAvatar: false,
      showMedia: false,
      animation: "scale",
      duration: 900,
    },
  },
];

export const SKELETON_PRESETS: StudioPreset[] = presets.map((preset) => ({
  ...preset,
  state: { ...DEFAULT_SKELETON_STATE, ...preset.state },
}));
